import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // Scan from docs/en directory
    },
  ],
};

export default sidebars;
