import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Sidebar for English docs (plugin already points to docs/en, so scan from root)
  englishSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Scan from plugin's path (docs/en)
    },
  ],
  // Sidebar for Urdu docs (plugin already points to docs/ur, so scan from root)
  urduSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Scan from plugin's path (docs/ur)
    },
  ],
};

export default sidebars;
